### ISSUE TITLE
Генерация ИсполняемыеСценарии

### ISSUE THREAD

**Issue by asosnoviy** [bia-technologies/edt-test-runner#1]
Генерировать метод автоматически, что бы не делать руками.

**Comment by alkoleft** [comment]
А как быть если модуль с тестами имеет другие экспортные методы, например для создания тестовых данных?

При автоформировании ИсполняемыеСценарии они будут добавлены автоматом. Можно конечно смотреть есть ли асерты внутри, но думаю это не панацея ибо проверки могут бы завернуты в отдельный метод с асертами.

**Comment by theshadowco** [comment]
например добавлять методы в области Тесты

**Comment by asosnoviy** [comment]
Я в целом смирился с этой необходимостью. =)

**Comment by alkoleft** [comment]
Реализовано в 9560466a84c71af113eaa66376cde5b59349c809
