### ISSUE TITLE
Предусмотреть возможность расположения тестов в основном проекте(конфигурации) 

### ISSUE THREAD

**Issue by ViktorErmakov** [bia-technologies/edt-test-runner#13]
Сейчас если модуль тестов расположить в основном проекте(конфигурации) то в конфигурации отладки нельзя его  выбрать.
Возможно кто то решит содержать/распространять модульные тесты прям в поставляемой конфигурации.

**Comment by theshadowco** [comment]
На данный момент не планируем реализовывать данную функциональность - тесты не должны входить в состав конфигурации, это не бизнес-код

**Comment by ViktorErmakov** [comment]
> На данный момент не планируем реализовывать данную функциональность - тесты не должны входить в состав конфигурации, это не бизнес-код

А если я разрабатываю библиотеку, которая будет встраиваться во многие решения, и хочу что бы вместе с библиотекой поставлялись и тесты, как готовый набор?

**Comment by theshadowco** [comment]
Так отлично - отдельно функциональность, отдельно - комплект тестов. Для распротранения одним комплектом можно воспользоваться сборкой файла setup, в который можно включить и бизнес-решение, и тесты, и документацию.
