### ISSUE TITLE
Не исчезает * - признак модифицированной вкладки модуля при сохранении.

### ISSUE THREAD

**Issue by ViktorErmakov** [bia-technologies/edt-test-runner#18]
в какой то момент ЕДТ входит в состояние когда вкладка формы модифицированная, имеет * в названии, не исчезает после сохранения модуля. 
Исчезает только когда идет переключение фокуса мышкой на любой другой элемент. 
По логам мне объявлено что это вот аддон наш делает.

**Comment by ViktorErmakov** [comment]
[trace.log](https://github.com/bia-technologies/edt-test-runner/files/10740849/trace.log)
[1.log](https://github.com/bia-technologies/edt-test-runner/files/10740854/1.log)

**Comment by alkoleft** [comment]
@ViktorErmakov Обнови плагин, ошибка из лога была исправлена не так давно
