### ISSUE TITLE
Генерировать мок метода по нажатию кнопки

### ISSUE THREAD

**Issue by Daabramov** [bia-technologies/edt-test-runner#27]
Будет очень удобно мокировать метод по кнопке, сейчас это занимает какое-то время.
	
Вижу себе это примерно так

1) Заходим в нужный модуль
2) Нажимаем ПКМ на метод который хотим мокнуть
3) Выбираем там "мокировать метод"
4) Метод попадает в расширение теста сразу с подготовленным кодом по мокированию

![image](https://github.com/bia-technologies/edt-test-runner/assets/31928832/6d0a9272-0db6-429e-9d33-5881935b0063)

**Comment by alkoleft** [comment]
Думал много раз на эту тему, как первый шаг к автоматизации мокирования,  ваша идея подойдет.

**Comment by alkoleft** [comment]
Также сделать возможным генерировать моки как из основного модуля (при фокусе на методе) так и в самом расширении (используя диалог выбора метода)
