### ISSUE TITLE
Ошибка: Не удалось найти тестовый метод

### ISSUE THREAD

**Issue by potoyalo** [bia-technologies/edt-test-runner#29]
![изображение](https://github.com/bia-technologies/edt-test-runner/assets/1996464/d91f77ac-01d5-489f-b9e9-13f121a565e6)

Возникает при попытке перехода из панели с результатами модульных тестов к методу теста в тестовом модуле. Чёткую закономерность пока не выявил, ошибка возникает не всегда, но чаще переход к тесту не работает, чем работает.

Буду дополнять, если появятся данные.

[log.log](https://github.com/bia-technologies/edt-test-runner/files/12217848/log.log)

**Comment by alkoleft** [comment]
Ловил в случаях когда EDT не построила модель документа, возможно нужно периодически проверять ее наличие.

**Comment by SeiOkami** [comment]
+ Ruby 2023.2.2
Иногда само ломается и потом само чинится (без перезагрузки ЕДТ)
