### ISSUE TITLE
Плагин не показывает результаты тестов

### ISSUE THREAD

**Issue by SeiOkami** [bia-technologies/edt-test-runner#34]
Тесты выполняются, отчет в worspace формируется, но плагин его не показывает и не добавляет в историю формирования
[ru.biatech.edt.junit.zip](https://github.com/bia-technologies/edt-test-runner/files/13053384/ru.biatech.edt.junit.zip)

В режиме предприятия всё формируется без ошибок

Пробовал очищать проект, переустанавливать плагин, очищать каталог плагина в worspace 
Другие проекты работают нормально. Ранее этот же проект тоже работал, но я его давно не открывал

EDT 2023.2.1

Запускаю без отладки. Но на консоли отладки выглядит так:
![image](https://github.com/bia-technologies/edt-test-runner/assets/42138875/8296c518-4a14-47b8-932a-36850afcdbfa)

**Comment by goodwinvu** [comment]
подтверждаю, на ЕДТ 2023.2.1 не показывает результаты тестов
при этом в логах ошибок нет

**Comment by Merkalov** [comment]
У меня и у коллеги тоже самое, после перехода на новую версию EDT плагин пришлось ставить заново, результаты тестов не отображает.

**Comment by alkoleft** [comment]
+1 на 2023.2.1

**Comment by Daabramov** [comment]
Пересоздание проекта помогает

**Comment by alkoleft** [comment]
Проверил, тут даже проект не надо пересоздавать. Пересоздать нужно конфигурацию запуска клиента 1с.

**Comment by Merkalov** [comment]
> Проверил, тут даже проект не надо пересоздавать. Пересоздать нужно конфигурацию запуска клиента 1с.
Это помогло, спасибо.
