### ISSUE TITLE
После запуска тестов из EDT удаляется файл junit.xml

### ISSUE THREAD

**Issue by Suban05** [bia-technologies/edt-test-runner#5]
1. Запускаю тесты из EDT
2. Расширение yaxunit успешно прогоняет тесты и создает файл с результатами
3. Результат тестов отображается в EDT, и файл с результатами удаляется.

Подскажите, пожалуйста, так должно быть?

**Comment by theshadowco** [comment]
да

**Comment by Suban05** [comment]
Спасибо!
